

DELETE http://localhost:3001/api/blogs/66fed6d5453a770199e06638
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlZWZlZTEiLCJpZCI6IjY2ZmVjOWE3ZWMxMWYyMDIyYmM2M2NmYSIsImlhdCI6MTcyNzk3MzgxMX0.UZf0qbPeB8iDB2CrkF99i0e92d0cFzohIkHiIJJAzy4
